version: '3'

services:
  bridge:
    image: nodejs_oebridge:latest
    restart: always
    depends_on:
      - webservice
    container_name: oebridge_${NAMEPREFIX}
    stop_grace_period: 5s
    networks:
      default:
        aliases:
          - bridge
    expose:
      - 3000
    environment:
      UrlEndPoint: 'http://webservice:8080/wsa/wsa1'
      LogLevel: 1
#      LogLevel: 2

  webservice:
    image: obliksaas_webservice:latest
    restart: always
#    depends_on:
#      - backend
    container_name: obliksaas_webservice_${NAMEPREFIX}
    stop_grace_period: 5s
    networks:
      default:
        aliases:
          - webservice
    expose:
      - 8080
#    extra_hosts:
#      - "appServiceHost:10.10.4.12"
    volumes:
      - ./log:/opt/tomcat/logs
      - ./webservice:/opt/tomcat/webapps/wsa/wsa1

#  Openedge Appserver appServiceHost:3100
#  backend:
#    image: backend:latest
#    restart: always
#    container_name: backend_${NAMEPREFIX}
#    networks:
#      default:
#        aliases:
#          - appServiceHost
#    ....

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
